using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

using System.Net;

public partial class LanguageAndComputer_Default : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {
        /*
        HttpCookie cookie = Request.Cookies["Authorization"];

        if (cookie == null)
        {
            lbInfo.Text = "未登入";
        }
        else
        {
            lbInfo.Text = cookie["Role"];

            if (cookie["Role"] == "Admin" || cookie["Role"] == "Boss" || cookie["Role"] == "Employee")
            {
                GridView1.AutoGenerateEditButton = true;
                GridView1.AutoGenerateDeleteButton = true;
                //GridView1.AutoGenerateSelectButton = true;
            }
        }
         * */

    }

    protected void GridView1_RowCommand(object sender, GridViewCommandEventArgs e)
    {
        HttpCookie cookie;
        int index = Convert.ToInt32(e.CommandArgument);

        if (e.CommandName == "AddToCart")
        {
            cookie = new HttpCookie("Product");
            cookie["Order"] = GridView1.Rows[index].Cells[0].Text;
            Response.Cookies.Add(cookie);
            Response.Redirect("~/Buy/ShoppingCart.aspx");
        }
        else if (e.CommandName == "Select")
        {
            cookie = new HttpCookie("Product2");
            cookie["Order"] = GridView1.Rows[index].Cells[0].Text;
            Response.Cookies.Add(cookie);
            Response.Redirect("~/Detailed_Information.aspx");
        }
    }
}
